### ISSUE TITLE
Output_dir flag not recognized on cluster computer

### ISSUE THREAD

**Issue by A-Thijssen** [Ararder/tidyGWAS#16]
Thanks for developing this useful tool!
 
I am able to succesfully use the tool on my laptop, but am running into an issue when running it on a cluster computer.
Specifically, the output_dir flag does not seem to be recognized. 

This is the command that I use (in an R session on an interactive node):

sumstats <- tidyGWAS::test_file
cleaned <- tidyGWAS(
  tbl = sumstats, 
  output_format = "csv",
  logfile = TRUE,
  dbsnp_path = "/gpfs/work5/0/prjs0778/dbSNP155",
  output_dir = "/gpfs/work5/0/prjs0778/tidied_sumstats/test_file"
)

The dbSNP path is found and used. The output and logfile are redirected to a scratch folder where I cannot locate them, the same happens when I remove the whole output_dir command, which suggests to me that the whole command is not recognized or taken into account. Do you have any idea what the issue might be?

Also, it would be helpful if the logfile is also printed to the screen in case of "logfile = TRUE" instead of only with "logfile = FALSE".

Thanks in advance!
Anaïs

**Comment by Ararder** [comment]
What version of tidyGWAS are you using? Previous versions used `outdir` instead of `output_dir`.
`packageVersion("tidyGWAS")` should return 0.8.0

**Comment by Ararder** [comment]
Excellent!
