### ISSUE TITLE
TidyGWAS for non-European population 

### ISSUE THREAD

**Issue by ssjj791** [Ararder/tidyGWAS#22]
I’m very interested in using this package! May I ask if it is implemented for all populations, such as EUR, EAS and AFR?

**Comment by Ararder** [comment]
Hi Jie,
tidyGWAS works for all populations, as there is no step that depends on reference data or assumptions that are ancestry specific. We will release allele frequencies to use for all major superpopulations to use with the `impute_freq` flag at some point in the future, but right now you can use your own file to provide an allele frequency reference when it's missing.

**Comment by ssjj791** [comment]
Thank you Arvid! Will try it!
